LOCAL_PATH  := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_SRC_FILES := $(wildcard $(abspath $(LOCAL_PATH))/*.cpp)

LOCAL_C_INCLUDES := $(PROJECT_INCLUDES)

LOCAL_CFLAGS  := $(PROJECT_CXXFLAGS)

LOCAL_LDFLAGS := $(PROJECT_LDFLAGS)

LOCAL_STATIC_LIBRARIES := $(PROJECT_STATIC_LIBS)
LOCAL_STATIC_LIBRARIES += libpandora.memory
LOCAL_STATIC_LIBRARIES += libpandora.log

LOCAL_SHARED_LIBRARIES := $(PROJECT_SHARED_LIBS)

LOCAL_LDLIBS += -llog

LOCAL_CPP_FEATURES := $(PROJECT_CPP_FEATURES)

LOCAL_MODULE := Pandora.Memory.Tester

LOCAL_INCLUDE_MODULE := memory
include $(MAKE_RULES)/find.library.android.make.rule
LOCAL_C_INCLUDES += $(_LOCAL_C_INCLUDES)

include $(BUILD_EXECUTABLE)
