include $(MAKE_RULE)/module.make.rule

all: $(MAKE_MODULES)

compile: $(COMPILE_MODULES)

link: $(LINK_MODULES)

build: $(BUILD_MODULES)

clean: $(CLEAN_MODULES)

release: $(RELEASE_MODULES)

.PHONY: all clean compile link